---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - vrouter.kojuro.date
  resources:
  - vrouterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vrouter.kojuro.date
  resources:
  - vrouterconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - vrouter.kojuro.date
  resources:
  - vrouterconfigs/status
  verbs:
  - get
  - patch
  - update
